resources:
# The repo with our Dockerfile
- name: py-repo
  type: git
  icon: github
  source:
    uri: https://github.com/l0stmylife/devops.git
    branch: main

# Where we will push the image to
- name: simple-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/py-microservice
    username: ((registry-username))
    password: ((registry-password))
    tag: latest

jobs:
- name: build-and-push
  plan:
  - get: py-repo
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: py-repo
      outputs:
      - name: image
      run:
        path: build
      params:
        CONTEXT: py-repo/docker/python-microservice
  - put: simple-image
    params:
      image: image/image.tar