#this pipeline is triggered by changes to the tracked git repo. the docker username and password must be passed as arguments to fly set to not expose secrets in git
resources:
# The repo with our Dockerfile and code
- name: py-repo
  type: git
  icon: github
  source:
    uri: https://github.com/l0stmylife/devops.git
    branch: main
    paths:
    - docker/*

# Where we will push the image to
- name: simple-image
  type: registry-image
  icon: docker
  source:
    repository: lostmylife/py-microservice
    username: ((registry-username.username))
    password: ((registry-password.password))
    tag: latest

jobs:
- name: build-and-push
  plan:
  - get: py-repo
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: py-repo
      outputs:
      - name: image
      run:
        path: build
      params:
        CONTEXT: py-repo/docker/python-microservice
  - put: simple-image
    params:
      image: image/image.tar