resources:
- name: parent-repo
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/l0stmylife/devops.git
    branch: main
    paths:
    - kubernetes/concourse/**

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: parent-repo
    trigger: true
  - set_pipeline: self
    file: parent-repo/kubernetes/concourse/parent.yml

#set an example pipeline
- name: set-example-pipelines
  public: true
  plan:
  - get: parent-repo
    trigger: true
    passed: [set-self]
  - set_pipeline: python-microservice
    file: parent-repo/kubernetes/concourse/build-image.yml